import { Typography } from "@/components";
import { CodeBlock } from "@/components/CodeBlock";

const str = `# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: \${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: \${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIPELINE_GENIUS }}
          channelId: live
          projectId: pipeline-genius
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
`;

export const LinkData = {
  label: "Home",
  href: "/",
};

export default function Home() {
  return (
    <Typography fullPage>
      <CodeBlock>{str}</CodeBlock>
    </Typography>
  );
}
